name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # La rama desde la cual se desplegará el contenido

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Clona el repositorio

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Acción para desplegar en GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token para autenticación
        publish_dir: './'  # Directorio a desplegar (raíz del repositorio)
