name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Desplegar solo cuando hay un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Clona el repositorio

    - name: Set up GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token para autenticación
        publish_branch: main  # Rama donde se desplegará (misma rama)
        publish_dir: ./  # Directorio a desplegar (raíz del repositorio)
