name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Desplegar solo cuando hay un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Clona el repositorio

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Rama de destino para GitHub Pages
        folder: './'  # Directorio a desplegar (raíz del repositorio)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token para autenticación
