name: Run Playwright Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Usamos Ubuntu como runner para los jobs

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Descargar el código fuente del repositorio

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run the Docker container
      run: |
        # Construir la imagen Docker
        docker build -t my-php-app .
        
        # Ejecutar el contenedor en segundo plano
        docker run -d -p 8000:8000 --name php-server my-php-app

        # Esperar a que el servidor PHP esté listo (opcionalmente puedes usar wait-for-it o un script similar)
        echo "Esperando a que el servidor PHP se inicie..."
        sleep 10  # Ajusta el tiempo de espera según sea necesario

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Run .NET Playwright Tests
      run: |
        # Ejecutar las pruebas de Playwright dentro del contenedor
        dotnet test  # Esto ejecutará las pruebas de .NET, que incluyen Playwright

    - name: Stop Docker container
      run: docker stop php-server  # Detener el contenedor después de las pruebas

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults/test-results.trx  # Subir los resultados de las pruebas
