name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Puedes cambiar a windows-latest si necesitas un entorno de Windows

    strategy:
      matrix:
        # Se pueden ejecutar pruebas en múltiples versiones de Node.js
        node-version: [18.x]  # Especifica la versión de Node.js que estás utilizando

    steps:
      # Paso 1: Realizar un "checkout" del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Paso 3: Instalar dependencias (incluyendo Playwright y Microsoft.Playwright.MSTest)
      - name: Install dependencies
        run: |
          npm install
          # Instalamos Playwright para ejecutar las pruebas
          npm install playwright

      # Paso 4: Instalar las dependencias de .NET (asumiendo que tienes un archivo .csproj)
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # O la versión que estés utilizando

      # Paso 5: Restaurar paquetes .NET
      - name: Restore .NET dependencies
        run: dotnet restore

      # Paso 6: Construir el proyecto .NET
      - name: Build .NET project
        run: dotnet build --configuration Release

      # Paso 7: Ejecutar las pruebas con Playwright
      - name: Run Playwright Tests
        run: |
          # Ejecutamos las pruebas MSTest (cambia el nombre del archivo si es necesario)
          dotnet test --logger "trx;LogFileName=test-results.trx"

      # Paso 8: Subir resultados de las pruebas (opcional)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.trx
          
      # Paso 9: Subir videos y trazas de Playwright (si se genera)
      - name: Upload Playwright trace and videos
        uses: actions/upload-artifact@v3
        with:
          name: playwright-traces
          path: playwright-traces/
