name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # O 'windows-latest' si estás usando Windows

    strategy:
      matrix:
        node-version: [18.x]  # Especifica la versión de Node.js que estás utilizando

    steps:
      # Paso 1: Realizar un "checkout" del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Cambia esta versión si estás utilizando otra versión de .NET

      # Paso 3: Instalar dependencias de Playwright para Ubuntu (en caso de que se ejecute en Linux)
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libatk1.0-0 libgbm1 libx11-xcb1
          sudo apt-get install -y libxcomposite1 libxdamage1 libxrandr2 libasound2
          sudo apt-get install -y libatspi2.0-0 libxtst6 libgtk-3-0 libdbus-1-3
          sudo apt-get install -y libxss1 libxt6 libgdk-pixbuf2.0-0 libsecret-1-0
          sudo apt-get install -y libnspr4

      # Paso 4: Restaurar dependencias de .NET especificando la ruta al archivo `.csproj`
      - name: Restore .NET dependencies
        run: |
          cd project/AppTest
          dotnet restore AppTest.csproj

      # Paso 5: Construir el proyecto .NET
      - name: Build .NET project
        run: |
          cd project/AppTest
          dotnet build AppTest.csproj --configuration Release

      # Paso 6: Ejecutar las pruebas con MSTest
      - name: Run Playwright Tests
        run: |
          cd project/AppTest
          dotnet test AppTest.csproj --logger "trx;LogFileName=test-results.trx"

      # Paso 7: Subir resultados de las pruebas
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.trx

      # Paso 8: Subir videos y trazas de Playwright
      - name: Upload Playwright trace and videos
        uses: actions/upload-artifact@v3
        with:
          name: playwright-traces
          path: playwright-traces/
